services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/var/www/
    working_dir: /var/www
    environment:
      PHP_IDE_CONFIG: "serverName=translations"